/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import conf.Conexao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import data.Relatorio;

/**
 *
 * @author lucas
 */
public class FormRelatorio extends javax.swing.JFrame {

    public Conexao conexao;
    public static Statement stmt;
    private Relatorio Relatorio;

    /**
     * Creates new form FormRelatorio
     */
    public FormRelatorio() throws SQLException {
        conexao = new Conexao();
        stmt = conexao.getConexao().createStatement();

        Relatorio = new Relatorio(select());     

        initComponents();
        
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##-####");
            jTextField1 = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRelatorio = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonTotalPorMes = new javax.swing.JButton();
        jButtonTotalPorAno = new javax.swing.JButton();
        jButtonTodosOsMeses = new javax.swing.JButton();
        jButtonPorProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Relatorio");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField1.setText("jTextField1");
        jTextField1.setName("Jteste"); // NOI18N

        tblRelatorio.setModel(Relatorio);
        tblRelatorio.setName("tblRelatorio"); // NOI18N
        jScrollPane2.setViewportView(tblRelatorio);

        jLabel2.setText("Data Mes-Ano");

        jButtonTotalPorMes.setText("Total por Mes");
        jButtonTotalPorMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalPorMesActionPerformed(evt);
            }
        });

        jButtonTotalPorAno.setText("Total por ano");
        jButtonTotalPorAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalPorAnoActionPerformed(evt);
            }
        });

        jButtonTodosOsMeses.setText("Todos os Meses");
        jButtonTodosOsMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodosOsMesesActionPerformed(evt);
            }
        });

        jButtonPorProduto.setText("Por Produto");
        jButtonPorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jButtonTotalPorMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTotalPorAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTodosOsMeses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPorProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTotalPorMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTotalPorAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTodosOsMeses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPorProduto)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTotalPorMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalPorMesActionPerformed

        if (jTextField1.getText().equals("  -    ")) {
            JOptionPane.showMessageDialog(null, "Campo DATA em branco!", "Atençao!", JOptionPane.INFORMATION_MESSAGE);
        } else {

            try {
                Relatorio.setResult(totalPorMes(jTextField1.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButtonTotalPorMesActionPerformed

    private void jButtonTotalPorAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalPorAnoActionPerformed
        try {
            Relatorio.setResult(totalPorAno());
        } catch (SQLException ex) {
            Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTotalPorAnoActionPerformed

    private void jButtonTodosOsMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodosOsMesesActionPerformed
        try {
            Relatorio.setResult(todosOsMeses());
        } catch (SQLException ex) {
            Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTodosOsMesesActionPerformed

    private void jButtonPorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorProdutoActionPerformed
        try {
            Relatorio.setResult(porProduto());
        } catch (SQLException ex) {
            Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPorProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormRelatorio().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormRelatorio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public ResultSet totalPorMes(String data) {
        ResultSet rs = null;
        String SQL = "SELECT  date_format(data_venda,'%m-%Y') A , CONVERT(CONCAT(SUM(total) , ' R$') USING utf8) B, '' as C\n"
                + "                FROM venda \n"
                + "                WHERE date_format(data_venda,'%m-%Y') = '" + data + "'\n"
                + "                GROUP BY date_format(data_venda,'%m-%Y') ";
        try {
            rs = stmt.executeQuery(SQL);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return rs;

    }

    public ResultSet totalPorAno() {
        ResultSet rs = null;
        String SQL = "SELECT date_format(data_venda,'%Y') A , CONVERT(CONCAT(SUM(total) , ' R$') USING utf8) B, '' as C\n"
                + "                FROM venda \n"
                + "                GROUP BY date_format(data_venda,'%Y')  ";
        try {
            rs = stmt.executeQuery(SQL);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return rs;

    }

    public ResultSet todosOsMeses() {
        ResultSet rs = null;
        String SQL = "SELECT date_format(data_venda,'%m-%Y') A , CONVERT(CONCAT(SUM(total) , ' R$') USING utf8) B, '' as C\n"
                + "                FROM venda \n"
                + "                GROUP BY date_format(data_venda,'%m-%Y') ";
        try {
            rs = stmt.executeQuery(SQL);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return rs;

    }

    public ResultSet porProduto() {
        ResultSet rs = null;
        String SQL = "SELECT p.descricao A, CONVERT(CONCAT(iv.preco_venda , ' R$') USING utf8) B, v.data_venda C\n"
                + "				FROM item_venda iv, produto p, venda v\n"
                + "				WHERE iv.produto_id = p.id\n"
                + "				AND iv.venda_id = v.id";
        try {
            rs = stmt.executeQuery(SQL);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return rs;

    }

    public ResultSet select() {
        ResultSet rs = null;
        String SQL = "SELECT '' A, '' B, '' C\n"
                + "FROM produto p\n"
                + "GROUP BY p.data_atlz";
        try {
            rs = stmt.executeQuery(SQL);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return rs;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPorProduto;
    private javax.swing.JButton jButtonTodosOsMeses;
    private javax.swing.JButton jButtonTotalPorAno;
    private javax.swing.JButton jButtonTotalPorMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblRelatorio;
    // End of variables declaration//GEN-END:variables
}
