/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import conf.Conexao;
import data.TabelaPagamento;
import data.TabelaProduto;
import data.TabelaTipoPagamento;
import java.awt.List;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static views.FormProduto.stmt;

public class FormPagamento extends javax.swing.JFrame {

  public Conexao conexao;
  public static Statement stmt;

  private TabelaTipoPagamento tabelaTipoPagamento;
  private TabelaPagamento tabelaPagamento;

  public FormPagamento() throws SQLException {

    conexao = new Conexao();
    stmt = conexao.getConexao().createStatement();

    tabelaPagamento = new TabelaPagamento(select());
    
    initComponents();
    preencherComboBox();
  }

  public void preencherComboBox() throws SQLException {
    //ArrayList<String> strList = new ArrayList<String>();
    String SQL = "select * from tipo_pag";
    ResultSet rs = stmt.executeQuery(SQL);

    while (rs.next()) {
      jComboBoxTipoPag.addItem(rs.getString("tipo"));
      System.out.println("Descricao-> " + rs.getString("tipo") + rs.getString(1));
    }

    //DefaultComboBoxModel defaultComboBox = new DefaultComboBoxModel(strList.toArray());
    //jComboBoxTipoPag.setModel(defaultComboBox);
    
     

  }//End

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLabelid = new javax.swing.JLabel();
    jFormattedTextFieldid = new javax.swing.JFormattedTextField();
    jLabelDesc = new javax.swing.JLabel();
    jFormattedTextFieldDesc = new javax.swing.JFormattedTextField();
    jLabelTaxa = new javax.swing.JLabel();
    jFormattedTextFieldTaxa = new javax.swing.JFormattedTextField();
    jLabelTipoPag = new javax.swing.JLabel();
    jComboBoxTipoPag = new javax.swing.JComboBox<>();
    jButtonTestar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTable1.setModel(tabelaPagamento);
    jScrollPane1.setViewportView(jTable1);

    jLabelid.setText("ID");

    jFormattedTextFieldid.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jFormattedTextFieldidActionPerformed(evt);
      }
    });

    jLabelDesc.setText("Descriçao");

    jLabelTaxa.setText("Taxa de Juros");

    jLabelTipoPag.setText("Tipo de Pagamento");

    jButtonTestar.setText("Objeto");
    jButtonTestar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonTestarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jLabelTaxa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldTaxa))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jLabelDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDesc))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jLabelid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(93, 93, 93)
            .addComponent(jButtonTestar))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelTipoPag)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBoxTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(366, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelid)
          .addComponent(jFormattedTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelDesc)
              .addComponent(jFormattedTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelTaxa)
              .addComponent(jFormattedTextFieldTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(jButtonTestar)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelTipoPag)
          .addComponent(jComboBoxTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(133, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jFormattedTextFieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldidActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jFormattedTextFieldidActionPerformed

  private void jButtonTestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestarActionPerformed
    // TODO add your handling code here:
    Object obj = jComboBoxTipoPag.getSelectedItem();
    System.out.println("Objeto aqui-> " + obj);
  }//GEN-LAST:event_jButtonTestarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        try {
          new FormPagamento().setVisible(true);
        } catch (SQLException ex) {
          Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    });
  }
  
  
  public ResultSet select() {
    ResultSet rs = null;
    String SQL = "select * from pagamento";
    try {
      rs = stmt.executeQuery(SQL);
    } catch (SQLException e) {
      e.printStackTrace();
    }
    return rs;
  }
  
  
  /*public void insert() {
    String SQL = "INSERT INTO pagamento(descricao,taxa, data_cad, data_atlz, id_tipo_pag_fk) " + "VALUES (?,?,now(),now(),?)";
    try {
      PreparedStatement ps = this.conexao.getConexao().prepareStatement(SQL);

      ps.setString(1, jFormattedTextFieldDesc.getText());
      ps.setFloat(2, Float.parseFloat(jFormattedTextFieldTaxa.getText()));
      ps.setInt(5, jComboBoxTipoPag.getSelectedObjects()));

      ps.executeUpdate();
      ps.close();
    } catch (SQLException ex) {
      ex.printStackTrace();
    }
  }*/

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonTestar;
  private javax.swing.JComboBox<Object> jComboBoxTipoPag;
  private javax.swing.JFormattedTextField jFormattedTextFieldDesc;
  private javax.swing.JFormattedTextField jFormattedTextFieldTaxa;
  private javax.swing.JFormattedTextField jFormattedTextFieldid;
  private javax.swing.JLabel jLabelDesc;
  private javax.swing.JLabel jLabelTaxa;
  private javax.swing.JLabel jLabelTipoPag;
  private javax.swing.JLabel jLabelid;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
