/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author doug
 */
public class TelaPrincipal extends javax.swing.JFrame {

  /**
   * Creates new form TelaPrincipal
   */
  public TelaPrincipal() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButtonVendas = new javax.swing.JButton();
    jButtonRelatorios = new javax.swing.JButton();
    jButtonPagamentos = new javax.swing.JButton();
    jButtonProdutos = new javax.swing.JButton();
    jLabelImgPrincipal = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenuCadastrar = new javax.swing.JMenu();
    jMenuItemProdutos = new javax.swing.JMenuItem();
    jMenuItemPagamento = new javax.swing.JMenuItem();
    jMenuSair = new javax.swing.JMenu();
    jMenuItemSair = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(null);

    jButtonVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/caixa.png"))); // NOI18N
    jButtonVendas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonVendasActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonVendas);
    jButtonVendas.setBounds(320, 230, 160, 130);

    jButtonRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/graphic.png"))); // NOI18N
    getContentPane().add(jButtonRelatorios);
    jButtonRelatorios.setBounds(600, 230, 160, 130);

    jButtonPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/payment.png"))); // NOI18N
    jButtonPagamentos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonPagamentosActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonPagamentos);
    jButtonPagamentos.setBounds(600, 390, 160, 130);

    jButtonProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/register-product.png"))); // NOI18N
    jButtonProdutos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonProdutosActionPerformed(evt);
      }
    });
    getContentPane().add(jButtonProdutos);
    jButtonProdutos.setBounds(320, 390, 160, 130);

    jLabelImgPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/online-store-header.51d264eff63b.png"))); // NOI18N
    getContentPane().add(jLabelImgPrincipal);
    jLabelImgPrincipal.setBounds(-180, 10, 1460, 630);

    jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jMenuCadastrar.setText("Cadastrar");

    jMenuItemProdutos.setText("Produtos");
    jMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItemProdutosActionPerformed(evt);
      }
    });
    jMenuCadastrar.add(jMenuItemProdutos);

    jMenuItemPagamento.setText("Formas de Pagamento");
    jMenuCadastrar.add(jMenuItemPagamento);

    jMenuBar1.add(jMenuCadastrar);

    jMenuSair.setText("Sair");
    jMenuSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuSairActionPerformed(evt);
      }
    });

    jMenuItemSair.setText("Sair do Sistema");
    jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItemSairActionPerformed(evt);
      }
    });
    jMenuSair.add(jMenuItemSair);

    jMenuBar1.add(jMenuSair);

    setJMenuBar(jMenuBar1);

    setSize(new java.awt.Dimension(1202, 715));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutosActionPerformed
    try {
      FormProduto tela = new FormProduto();
      tela.setVisible(true);
    } catch (SQLException ex) {
      Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
    }

  }//GEN-LAST:event_jButtonProdutosActionPerformed

  private void jButtonPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagamentosActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonPagamentosActionPerformed

  private void jButtonVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendasActionPerformed
    // TODO add your handling code here:
    try {
      FormProduto tela = new FormProduto();
      tela.setVisible(true);
    } catch (SQLException ex) {
      Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_jButtonVendasActionPerformed

  private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed

  }//GEN-LAST:event_jMenuSairActionPerformed

  private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_jMenuItemSairActionPerformed

  private void jMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutosActionPerformed
    try {
      FormProduto tela = new FormProduto();
      tela.setVisible(true);
    } catch (SQLException ex) {
      Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_jMenuItemProdutosActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaPrincipal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonPagamentos;
  private javax.swing.JButton jButtonProdutos;
  private javax.swing.JButton jButtonRelatorios;
  private javax.swing.JButton jButtonVendas;
  private javax.swing.JLabel jLabelImgPrincipal;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenu jMenuCadastrar;
  private javax.swing.JMenuItem jMenuItemPagamento;
  private javax.swing.JMenuItem jMenuItemProdutos;
  private javax.swing.JMenuItem jMenuItemSair;
  private javax.swing.JMenu jMenuSair;
  // End of variables declaration//GEN-END:variables
}
